[program:digify-queue]
command=/usr/bin/php /var/www/artisan queue:work --tries=3 --backoff=10
directory=/var/www
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/digify-queue.log
stderr_logfile=/var/log/supervisor/digify-queue-error.log
